import { getEnv } from '../utils/get-env';

export const env = {
  PORT: getEnv('PORT'),
  NODE_ENV: getEnv('NODE_ENV'),
  JWT_SECRET: getEnv('JWT_SECRET'),
  VERIFICATION_COOKIE_NAME: getEnv('VERIFICATION_COOKIE_NAME'),
  AUTH_COOKIE_NAME: getEnv('AUTH_COOKIE_NAME'),
  GOOGLE_CLIENT_ID: getEnv('GOOGLE_CLIENT_ID'),
  GOOGLE_CLIENT_SECRET: getEnv('GOOGLE_CLIENT_SECRET'),
  GOOGLE_REDIRECT_URI: getEnv('GOOGLE_REDIRECT_URI'),
  FRONTEND_URL: getEnv('FRONTEND_URL'),
} as const;
